### ISSUE TITLE
Looking for contributors?

### ISSUE THREAD

**Issue by vBubbaa** [DaltonKirk/tarkov-bullets#3]
Hey @DaltonKirk ,

I'm a Vue developer that happens to also loves Tarkov. I've been wanting to work on some Open Source stuff. Do you want any help with contributing/development of this site? I would be more than willing to help out with this project. Let me know if you want to get in touch!

Best Regards,
Michael James

**Comment by DaltonKirk** [comment]
Hi @vBubbaa,

Yeah that sounds great! I'd love to collaborate.

**Comment by vBubbaa** [comment]
If you have Discord, my @ is Tyler | vBubbaa#7954. Might be the easiest way, but if you have another way in mind let me know! I love Tarkov and Vue so I'm open to helping with whatever :)
